import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  appShell: { flex: 1, backgroundColor: "#F8FAFC" },
  safeArea: { flex: 1, backgroundColor: "#F8FAFC" },
  safeAreaContent: { flex: 1, backgroundColor: "#F8FAFC", padding: 16 },
  settingsScrollContent: { flexGrow: 1, paddingBottom: 16 },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
  },
  loadingText: { marginTop: 12, fontSize: 16, color: "#1E293B" },
  topBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: "#0F172A",
    minHeight: 56,
    width: "100%",
    marginBottom: 0,
  },
  settingsTopBar: { marginBottom: 12, paddingLeft: 14, paddingRight: 14 },
  topBarLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 1,
  },
  headerMeta: { flexShrink: 1 },
  heading: { color: "#0F172A", fontSize: 18, fontWeight: "700" },
  topBarHeading: { color: "#F8FAFC" },
  serverText: { color: "#CBD5E1", fontSize: 10, marginTop: 2, maxWidth: 160 },
  topBarActions: { flexDirection: "row", alignItems: "center", gap: 6 },
  iconButton: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#1E293B",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryActionButton: {
    backgroundColor: "#4F46E5",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  secondaryActionContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  secondaryActionText: { color: "#FFF", fontWeight: "700", fontSize: 12 },
  secondaryActionButtonDisabled: { opacity: 0.5 },
  connectionRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#E2E8F0",
  },
  statusDot: { width: 10, height: 10, borderRadius: 999, marginRight: 8 },
  connectionLabel: { color: "#1E293B", fontSize: 12, flexShrink: 1 },
  drawerOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 4,
  },
  drawerScrim: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(15, 23, 42, 0.25)",
  },
  drawerPanel: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 260,
    backgroundColor: "#FFF",
    borderRightWidth: 1,
    borderRightColor: "#E2E8F0",
    paddingTop: 21,
    paddingHorizontal: 12,
    paddingBottom: 16,
  },
  drawerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  drawerTitle: { color: "#0F172A", fontSize: 16, fontWeight: "700" },
  drawerCloseButton: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#4F46E5",
  },
  drawerNewChatButton: {
    backgroundColor: "#4F46E5",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 12,
  },
  drawerNewChatContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  drawerNewChatText: { color: "#FFF", fontSize: 12, fontWeight: "700" },
  historyList: { gap: 8 },
  historyItemRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  historyItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F1F5F9",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  historyItemActive: { backgroundColor: "#4F46E5" },
  historyActions: { flexDirection: "row", alignItems: "center", gap: 6 },
  historyActionButton: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "#E2E8F0",
    alignItems: "center",
    justifyContent: "center",
  },
  historyItemText: { color: "#1E293B", fontSize: 12, fontWeight: "600" },
  historyItemTextActive: { color: "#FFF" },
  historyTimestamp: { color: "#64748B", fontSize: 10, marginTop: 4 },
  historyTimestampActive: { color: "#E2E8F0" },
  modelSection: {
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 6,
    backgroundColor: "#F8FAFC",
  },
  label: {
    color: "#0F172A",
    fontSize: 15,
    fontWeight: "700",
    flexShrink: 1,
  },
  settingsLabelSpacing: { marginTop: 12 },
  settingsSectionTitle: {
    color: "#0F172A",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 10,
  },
  modelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  dropdown: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#4F46E5",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    minWidth: 0,
  },
  dropdownText: {
    color: "#FFF",
    fontWeight: "600",
    fontSize: 12,
    flexShrink: 1,
    minWidth: 0,
    textAlign: "left",
    maxWidth: "80%",
    overflow: "hidden",
  },
  chatContainer: {
    position: "relative",
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  keyboardStickyComposer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#FFF",
  },
  chatScreen: { flex: 1, backgroundColor: "#F8FAFC" },
  chatScrollContainer: { flex: 1, backgroundColor: "#F8FAFC" },
  chatScrollContent: {
    flexGrow: 1,
    justifyContent: "flex-end",
    paddingBottom: Platform.OS === "ios" ? 12 : 16,
    paddingTop: 12,
  },
  chatList: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 20,
    gap: 10,
  },
  emptyChatText: {
    color: "#64748B",
    fontSize: 14,
    textAlign: "center",
    marginTop: 20,
  },
  messageBubble: {
    maxWidth: "82%",
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginVertical: 6,
    marginHorizontal: 16,
  },
  messagePressable: { flexDirection: "column" },
  userBubble: { alignSelf: "flex-end", backgroundColor: "#4F46E5" },
  assistantBubble: { alignSelf: "flex-start", backgroundColor: "#E2E8F0" },
  messageText: { color: "#0F172A", fontSize: 14, lineHeight: 20 },
  userMessageText: { color: "#FFF" },
  copiedHint: {
    color: "#E2E8F0",
    fontSize: 10,
    marginTop: 6,
    fontWeight: "600",
  },
  messageActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 8,
    marginTop: 6,
  },
  messageActionButton: {
    width: 24,
    height: 24,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  inputComposer: {
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === "ios" ? 8 : 6,
    backgroundColor: "#FFF",
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    marginTop: 0,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  input: {
    flex: 1,
    minHeight: 44,
    maxHeight: 112,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 11,
    backgroundColor: "#F1F5F9",
    fontSize: 14,
    color: "#0F172A",
    textAlignVertical: "center",
  },
  composerIconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  sendButton: {
    backgroundColor: "#4F46E5",
    width: 44,
    minHeight: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  sendButtonDisabled: { backgroundColor: "#4338CA", opacity: 0.75 },
  sendButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  sendButtonText: { color: "#FFF", fontWeight: "700" },
  sendButtonTextDisabled: {
    color: "#E2E8F0",
    opacity: 0.9,
    fontWeight: "700",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.5)",
    justifyContent: "center",
    alignItems: "stretch",
    padding: 0,
  },
  modalCard: {
    width: "100%",
    maxWidth: "100%",
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 16,
  },
  dialogCard: {
    width: "100%",
    maxWidth: "100%",
    alignSelf: "stretch",
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  modalTitle: {
    color: "#0F172A",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 12,
  },
  dialogMessage: {
    color: "#334155",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
  },
  dialogActions: { flexDirection: "row", justifyContent: "flex-end", gap: 10 },
  dialogButton: { flex: 0, minWidth: 100 },
  modelOption: {
    backgroundColor: "#F1F5F9",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 8,
  },
  modelOptionSelected: { backgroundColor: "#4F46E5" },
  modelOptionText: { color: "#0F172A", fontWeight: "600" },
  modelOptionTextSelected: { color: "#FFF" },
  renameInput: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#0F172A",
    marginBottom: 12,
  },
  renameActions: { flexDirection: "row", gap: 10 },
  renameActionButton: { flex: 1 },
  languageSelector: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  languageChip: {
    backgroundColor: "#F1F5F9",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  languageChipSelected: { backgroundColor: "#4F46E5" },
  languageChipText: {
    color: "#0F172A",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  languageChipTextSelected: { color: "#FFF" },
  settingsCard: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    marginHorizontal: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  valueText: { color: "#0F172A", fontSize: 16, marginBottom: 12 },
  buttonRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
    alignItems: "stretch",
  },
  primaryButton: {
    backgroundColor: "#4F46E5",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 46,
  },
  primaryButtonDisabled: { backgroundColor: "#4F46E5", opacity: 0.5 },
  primaryButtonTextDisabled: { color: "#FFF", opacity: 0.8 },
  secondaryButton: {
    backgroundColor: "#E2E8F0",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 46,
  },
  secondaryButtonDisabled: { opacity: 0.6 },
  primaryButtonText: { color: "#FFF", fontWeight: "700", textAlign: "center" },
  secondaryButtonText: {
    color: "#0F172A",
    fontWeight: "700",
    textAlign: "center",
  },
  fullWidth: { flex: 1 },
  buttonDisabled: { opacity: 0.6 },
  modelList: { gap: 8 },
  modelListItem: {
    color: "#1E293B",
    backgroundColor: "#F1F5F9",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginTop: 8,
  },
  emptyText: { color: "#64748B" },
  typingBubble: {
    alignSelf: "flex-start",
    minWidth: 72,
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  typingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 18,
  },
  typingRowCompact: { gap: 4, minHeight: 14 },
  typingDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#94A3B8",
  },
  typingDotCompact: { width: 6, height: 6 },
});
